<a href="https://colab.research.google.com/github/LucasFXimenes/bancodedados/blob/main/imersaodados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import pandas e nomeia como pd
#df é a variavél responsavel por ler o arquivo pandas em formato csv
#df.head()->exibe a base de dados
#df.info()->exibe as colunas da tabela e os tipos dos dados
#df.describe()->exibe a quantidade total e valores númericos dos dados
#df.shape->atributo responsável por exibir a quantia total de linhas e o numero de colunas em uma tupla
#criei as variáveis linhas e colunas para receber os 2 valores do vetor df.shape começando da posição 0
#df.columns->exibe somente o nome das colunas da tabela
#df["nome da coluna"].value_count()->exibe a distribuição dos dados em contagem de cada coluna
#df["nome da coluna"].replace->renomeia as linhas da coluna
#df.describe(include="object")->maneira mais intuitiva de visualizar e compreender os dados
#df.isnull()->exibe true pra dados nulos e false aonde não possuir dado nulo (só exibe os 5 primeiros e os 5 ultimos dados)
#df.isnull().sum()->soma todos dados nulos e exibe em qual coluna estão
#df['ano'].unique()->método exibe quais são os valores unicos dentro dessa coluna
#df[df.isnull().any(axis=1)]->filtrando tudo da base que o isnull() é true e exibe

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [4]:
df.head(10)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M
5,2025.0,EN,FT,Data Engineer,80000,USD,80000,US,0,US,M
6,2025.0,SE,FT,Data Scientist,185000,USD,185000,US,0,US,M
7,2025.0,SE,FT,Data Scientist,148000,USD,148000,US,0,US,M
8,2025.0,MI,FT,Data Scientist,135000,USD,135000,CA,0,CA,M
9,2025.0,MI,FT,Data Scientist,108000,USD,108000,CA,0,CA,M

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [6]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [7]:
df.shape

(133349, 11)

In [8]:
linhas, colunas = df.shape[0], df.shape[1]
print(f"linhas: {linhas}")
print(f"colunas: {colunas}")

linhas: 133349
colunas: 11

In [9]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [10]:
#prompt 'traduza pra mim todas as colunas do dataframe df para português brasileiro'
df.columns = [
    'ano',
    'senioridade',
    'contrato',
    'cargo',
    'salario',
    'moeda',
    'usd',
    'residencia',
    'remoto',
    'empresa',
    'tamanho_empresa'
]

In [11]:
df.columns

Index(['ano', 'senioridade', 'contrato', 'cargo', 'salario', 'moeda', 'usd',
       'residencia', 'remoto', 'empresa', 'tamanho_empresa'],
      dtype='object')

In [12]:
df["senioridade"].value_counts()

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [13]:
df["contrato"].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [14]:
df["remoto"].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [15]:
df["tamanho_empresa"].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [16]:
#prompt:traduza para portugues as categorias da coluna "senioridade" do dataframe df
df['senioridade'] = df['senioridade'].replace({
    'SE': 'Senior',
    'MI': 'Medio',
    'EN': 'Junior',
    'EX': 'Executivo'
})

df['senioridade'].value_counts()

senioridade
Senior       77241
Medio        40465
Junior       12443
Executivo     3200
Name: count, dtype: int64

In [17]:
#prompt:traduza para portugues as categorias da coluna "contrato" do dataframe df
df['contrato'] = df['contrato'].replace({
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Meio Periodo',
    'FL': 'Freelancer'
})

df['contrato'].value_counts()

contrato
Tempo Integral    132563
Contrato             394
Meio Periodo         376
Freelancer            16
Name: count, dtype: int64

In [18]:
#prompt:traduza para portugues as categorias da coluna "remoto" do dataframe df
df['remoto'] = df['remoto'].replace({
    0: 'Presencial',
    100: 'Remoto',
    50: 'Híbrido'
})

df['remoto'].value_counts()

remoto
Presencial    105312
Remoto         27718
Híbrido          319
Name: count, dtype: int64

In [19]:
df.describe(include="object")

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Tempo Integral,Data Scientist,USD,US,Presencial,US,M
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [20]:
df.isnull()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [21]:
df.isnull().sum()

ano                10
senioridade         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

In [22]:
df['ano'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [23]:
df[df.isnull().any(axis=1)]

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,Senior,Tempo Integral,Product Manager,184500,USD,184500,US,Presencial,US,M
59692,NaN,Medio,Tempo Integral,Engineer,110000,USD,110000,DE,Presencial,DE,M
59710,NaN,Junior,Tempo Integral,Data Scientist,208800,USD,208800,US,Presencial,US,M
59759,NaN,Senior,Tempo Integral,Software Engineer,135000,USD,135000,US,Presencial,US,M
59789,NaN,Senior,Tempo Integral,Engineer,112000,USD,112000,US,Presencial,US,M
131000,NaN,Senior,Tempo Integral,Machine Learning Engineer,163800,USD,163800,US,Presencial,US,M
131006,NaN,Senior,Tempo Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,M
133054,NaN,Junior,Tempo Integral,Data Scientist,40000,USD,40000,JP,Remoto,MY,L
133281,NaN,Medio,Tempo Integral,Machine Learning Engineer,180000,PLN,46597,PL,Remoto,PL,L
133317,NaN,Medio,Tempo Integral,Data Scientist,130000,USD,130000,US,Híbrido,US,L

In [42]:
#FILTRANDO DADOS NULOS UTILIZANDO A MÉDIA

#biblioteca que permite dados nulos
import numpy as np

#criando um dataframe (df_salarios) para teste com as colunas nome e salário
#np.nan->são os dados nulos
df_salarios = pd.DataFrame({
    "nome":["Lucas","Juliana","Raphael","Junior","Satie"],
    "salario":[np.nan,4500,5000,np.nan,100000]
  })

'''
criando a coluna (salario_media) e recebendo a fórmula .fillna para preencher os campos nulos
df_salarios -> base de dados
salario_media -> coluna nova
dentro da base na coluna média iremos prencher os valores nulos(fill.na) com a média ('salario'.mean())
.round2 serve para fazer o arrendodamento do valor
criando a coluna salario_mediana para prencher os campos nulos com o median
.median serve também para calcular a média porém se tiver um valor fora do padrão ele desconsidera da média
'''

df_salarios["salario_media"] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))

df_salarios["salario_mediana"] = df_salarios['salario'].fillna(df_salarios['salario'].median())
df_salarios

      nome   salario  salario_media  salario_mediana
0    Lucas       NaN        36500.0           5000.0
1  Juliana    4500.0         4500.0           4500.0
2  Raphael    5000.0         5000.0           5000.0
3   Junior       NaN        36500.0           5000.0
4    Satie  100000.0       100000.0         100000.0

In [50]:
#ALTERANDO VALORES NULOS PELO VALOR SUPERIOR E ANTERIOR

#criando o dataframe temperatura com as colunas dia e temperatura
df_temperaturas = pd.DataFrame({
    "Dia": ['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
    "Temperatura": [30, np.nan, np.nan, 28, 27, np.nan, 26]
})

#criando a coluna preenchido_ffil com a funcão de caso tenha um valor nulo preenche com o valor anterior .ffill()
#criando a coluna preenchido_bfil com a função de caso tenha um valor nulo preenche com o valor o próximo valor .bfill()
df_temperaturas["preenchido_ffill"] = df_temperaturas["Temperatura"].ffill()
df_temperaturas["preenchido_bfill"] = df_temperaturas["Temperatura"].bfill()

print(df_temperaturas)

       Dia  Temperatura  preenchido_ffill  preenchido_bfill
0  Segunda         30.0              30.0              30.0
1    Terça          NaN              30.0              28.0
2   Quarta          NaN              30.0              28.0
3   Quinta         28.0              28.0              28.0
4    Sexta         27.0              27.0              27.0
5   Sábado          NaN              27.0              26.0
6  Domingo         26.0              26.0              26.0

In [54]:
#ALTERANDO VALORES NULOS PARA STRING 'Não informado'

#criando o dataframe df_cidades com as colunas nome e cidade
df_cidades = pd.DataFrame({
    'nome':['Lucas','Juliana','Raphael','Junior','Satie'],
    'cidade':['SP',np.nan,'BH','RJ',np.nan]
})
#adicionando ao dataframe uma coluna cidade_preenchida
#os valores nulos ficaram como "Não Informado"
df_cidades['cidade_preenchida'] = df_cidades['cidade'].fillna('Não informado')
df_cidades

      nome cidade cidade_preenchida
0    Lucas     SP                SP
1  Juliana    NaN     Não informado
2  Raphael     BH                BH
3   Junior     RJ                RJ
4    Satie    NaN     Não informado

In [58]:
#criando uma váriavel df_limpo que recebe nosso df e utiliza a função dropna() para excluir campos nulos
df_limpo = df.dropna()
#somar e exibir todos os valores da variavel df_limpo que são nulos no caso 0 por conta da função anterior
df_limpo.isnull().sum()

ano                0
senioridade        0
contrato           0
cargo              0
salario            0
moeda              0
usd                0
residencia         0
remoto             0
empresa            0
tamanho_empresa    0
dtype: int64

In [59]:
#exibindo o dataframe tratado, repare que o ano está no valor float
df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M
1,2025.0,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M
2,2025.0,Medio,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M
3,2025.0,Medio,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M
4,2025.0,Junior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M

In [60]:
#aqui conseguimos realmente verificar que o tipo do dado ano está em float
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ano              133339 non-null  float64
 1   senioridade      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 12.2+ MB

In [64]:
#ALTERANDO TIPO DO DADO
#nossa base de dados df_limpo recebe df_limpo novamente mas será reconfigurado(assign) alterando a coluna ano
#no caso ele pega o ano antigo e modifica o tipo(.astype) pra int64
df_limpo = df_limpo.assign(ano = df_limpo['ano'].astype('int64'))
df_limpo

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M
1,2025,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M
2,2025,Medio,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M
3,2025,Medio,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M
4,2025,Junior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M
...,...,...,...,...,...,...,...,...,...,...,...
133344,2020,Senior,Tempo Integral,Data Scientist,412000,USD,412000,US,Remoto,US,L
133345,2021,Medio,Tempo Integral,Principal Data Scientist,151000,USD,151000,US,Remoto,US,L
133346,2020,Junior,Tempo Integral,Data Scientist,105000,USD,105000,US,Remoto,US,S
133347,2020,Junior,Contrato,Business Data Analyst,100000,USD,100000,US,Remoto,US,L
133348,2021,Senior,Tempo Integral,Data Scientist,7000000,INR,94665,IN,Híbrido,IN,L